In [1]:
import pandas as pd

diabetes = pd.read_csv('data/diabetes.csv')
diabetes.shape

(768, 9)

In [2]:
diabetes.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1

In [3]:
diabetes.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [4]:
print diabetes[diabetes.Glucose == 0].shape
diabetes.Glucose = diabetes.Glucose.replace(0,None)
print diabetes[diabetes.Glucose == 0].shape

(5, 9)
(0, 9)

In [5]:
cols = ['BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
print diabetes[cols].head(10)

for col in cols:
    print col, ": ", diabetes[diabetes[col] == 0].shape
    diabetes.loc[diabetes[col] == 0, col] = None
    print col, ": ", diabetes[diabetes[col] == 0].shape

print diabetes.info()

   BloodPressure  SkinThickness  Insulin   BMI  DiabetesPedigreeFunction  Age
0             72             35        0  33.6                     0.627   50
1             66             29        0  26.6                     0.351   31
2             64              0        0  23.3                     0.672   32
3             66             23       94  28.1                     0.167   21
4             40             35      168  43.1                     2.288   33
5             74              0        0  25.6                     0.201   30
6             50             32       88  31.0                     0.248   26
7              0              0        0  35.3                     0.134   29
8             70             45      543  30.5                     0.158   53
9             96              0        0   0.0                     0.232   54
BloodPressure :  (35, 9)
BloodPressure :  (0, 9)
SkinThickness :  (227, 9)
SkinThickness :  (0, 9)
Insulin :  (374, 9)
Insulin :  (0, 9)
BMI :  (11, 9)
BMI :  (0, 9)
DiabetesPedigreeFunction :  (0, 9)
DiabetesPedigreeFunction :  (0, 9)
Age :  (0, 9)
Age :  (0, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
Pregnancies                 768 non-null int64
Glucose                     768 non-null int64
BloodPressure               733 non-null float64
SkinThickness               541 non-null float64
Insulin                     394 non-null float64
BMI                         757 non-null float64
DiabetesPedigreeFunction    768 non-null float64
Age                         768 non-null float64
Outcome                     768 non-null int64
dtypes: float64(6), int64(3)
memory usage: 54.1 KB
None

In [6]:
diabetes.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,733.000000,541.000000,394.000000,757.000000,768.000000,768.000000,768.000000
mean,3.845052,121.514323,72.405184,29.153420,155.548223,32.457464,0.471876,33.240885,0.348958
std,3.369578,30.531191,12.382158,10.476982,118.775855,6.924988,0.331329,11.760232,0.476951
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,64.000000,22.000000,76.250000,27.500000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,29.000000,125.000000,32.300000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,36.000000,190.000000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [7]:
diabetes.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.128749,0.214178,0.100239,0.082171,0.021719,-0.033523,0.544341,0.221898
Glucose,0.128749,1.000000,0.225919,0.225000,0.580586,0.230860,0.137932,0.267282,0.490122
BloodPressure,0.214178,0.225919,1.000000,0.226839,0.098272,0.289230,-0.002805,0.330107,0.170589
SkinThickness,0.100239,0.225000,0.226839,1.000000,0.184888,0.648214,0.115016,0.166816,0.259491
Insulin,0.082171,0.580586,0.098272,0.184888,1.000000,0.228050,0.130395,0.220261,0.303454
BMI,0.021719,0.230860,0.289230,0.648214,0.228050,1.000000,0.155382,0.025841,0.313680
DiabetesPedigreeFunction,-0.033523,0.137932,-0.002805,0.115016,0.130395,0.155382,1.000000,0.033561,0.173844
Age,0.544341,0.267282,0.330107,0.166816,0.220261,0.025841,0.033561,1.000000,0.238356
Outcome,0.221898,0.490122,0.170589,0.259491,0.303454,0.313680,0.173844,0.238356,1.000000

In [8]:
import numpy as np

diabetes_normalized = diabetes
for col in diabetes_normalized.columns.values:
    col_mean = np.mean(diabetes[col])
    col_sd = np.std(diabetes[col])
    diabetes_normalized[col] = (diabetes_normalized[col] - col_mean)/col_sd

print diabetes_normalized.mean()
print diabetes_normalized.std()



# Or, in a single step,
# diabetes_normalized = (diabetes - diabetes.mean()) / diabetes.std()

diabetes_normalized.Outcome = diabetes_normalized.Outcome > 0.0

Pregnancies                 2.544261e-17
Glucose                    -1.487525e-16
BloodPressure              -5.511735e-16
SkinThickness              -2.842253e-17
Insulin                     4.790302e-18
BMI                         3.805117e-16
DiabetesPedigreeFunction    2.398978e-16
Age                         1.857600e-16
Outcome                     2.408374e-16
dtype: float64
Pregnancies                 1.000652
Glucose                     1.000652
BloodPressure               1.000683
SkinThickness               1.000925
Insulin                     1.001271
BMI                         1.000661
DiabetesPedigreeFunction    1.000652
Age                         1.000652
Outcome                     1.000652
dtype: float64

In [9]:
diabetes_normalized.head(6)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,0.639947,0.868061,-0.032746,0.558557,NaN,0.165097,0.468492,1.425995,True
1,-0.844885,-1.196747,-0.517645,-0.014657,NaN,-0.846404,-0.365061,-0.190672,False
2,1.233880,2.015177,-0.679278,NaN,NaN,-1.323254,0.604397,-0.105584,True
3,-0.844885,-1.065648,-0.517645,-0.587871,-0.518847,-0.629654,-0.920763,-1.041549,False
4,-1.141852,0.507539,-2.618874,0.558557,0.104968,1.537847,5.484909,-0.020496,True
5,0.342981,-0.180730,0.128887,NaN,NaN,-0.990904,-0.818079,-0.275760,False

In [10]:
cols = [c for c in diabetes_normalized.columns.values if c not in ['Outcome']]

for col in cols:
    new_col = col+'_isnull'
    diabetes_normalized[new_col] = diabetes_normalized[col].fillna(1.0,inplace=True)
    diabetes_normalized.loc[diabetes_normalized[new_col] != 1.0,new_col] = 0.0
    
diabetes_normalized.shape

(768, 17)